### ISSUE TITLE
broken profile picture

### ISSUE THREAD

**Issue by azarbara** [YAFNET/YAFNET-DNN#7]
in the latest version for dnn YAF_DNN_2.12.0-5608 the profile pic doesn't show
![capture](https://cloud.githubusercontent.com/assets/5406334/4953697/57861e24-6684-11e4-9f2a-6e960e295911.JPG)

**Comment by w8tcha** [comment]
Can you reproduce the issue with YAF 2.2.0 BETA 1?

**Comment by azarbara** [comment]
the problem solved in new version. :+1:

**Comment by abomadi** [comment]
Fixed thx

**Comment by abomadi** [comment]
seems not fixed yet, now the avatar displays correctly but users that have DNN profile image are not synced too.

**Comment by w8tcha** [comment]
Sorry to ask the same question again but did you try to run the user importer? and what happens when you change the profile image in your profile.

Profiles are only synced if something has changed.
